- name: copying default.conf file
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify:
    restart nginx

- name: copying index.html file
  copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html
    
