-
  name: Update nameserver entry into resolv.conf file on localhost
  hosts: localhost
  vars:
      car_model: "BMW M3"
      country_name: "USA"
      title: "Systems Engineer"
  tasks:
    -
      name: Print my car model
      command: echo "My car's model is {{ car_model }}"
      register: car_model

    - debug:
          var: car_model.stdout_lines              

    -
      name: Print my country
      command: echo "I live in the {{ country_name }}"
      register: country_name

    - debug:
          var: country_name.stdout_lines 

    -
      name: Print my title
      command: echo "I work as a {{ title }}"
      register: title

    - debug:
          var: title.stdout_lines
