---
- hosts: ox
  remote_user: root
  tasks:

  - name: removing devops user
    user:
      name: devops
      uid: 1001
      group: devops
      state: absent

  - name: removing devops group
    group: 
      name: devops
      state: absent

  - name: Adding repo
    yum:
      name: http://download.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm 
      state: present

  - name: removing Htop utility
    yum: 
      name: htop
      state: absent
      update_cache: yes

  - name: removing nginx repo
    yum_repository:
      name: nginx repo
      description: nginx repo
      baseurl: http://nginx.org/packages/mainline/centos/6/x86_64/
      state: absent

  - name: unInstall nginx and ensure it is latest
    yum: 
      name: nginx
      state: absent
