---
# tasks file for python
- name: Install EPEL Repo
  yum:
      name: epel-release
      state: installed

- name: Install Dependencies
  yum:
      name: "{{ item }}"
      state: installed
  with_items:
      - python
      - python-setuptools
      - python-devel
      - python-pip
      - MySQL-python

